language: vim

install:
  - pip install --requirement requirements.txt

before_script: |
    mkdir -p ~/.vim/bundle
    cd ~/.vim/bundle
    git clone https://github.com/junegunn/vader.vim.git
    cd -

    git clone https://github.com/vim/vim
    cd vim
    ./configure --with-features=huge
    make
    sudo make install
    cd -

script: invoke
