---
language: python

python:
  - "3.5"

before_script: |
    sudo inv setup

    git clone https://github.com/vim/vim
    cd vim
    ./configure --with-features=huge
    make
    sudo make install
    cd -

script: invoke
